### ISSUE TITLE
Distributed training with Kubernetes

### ISSUE THREAD

**Issue by jlewi** [google-research/batch-ppo#17]
Opening this issue to start a discussion about whether it would be worth investing to make it easy to run tensorflow agents K8s.

For some inspiration you can look at [TfJob CRD](https://github.com/tensorflow/k8s/blob/master/tf_job_design_doc.md).

Some questions:
  1. Is there a need to be able to distribute the environments across multiple machines?
  1. What is the communication pattern between the simulations and TensorFlow job?
          * Is data fetched from all simulations simultaneously?
          * Does each simulation need to be individually addressable?

**Comment by danijar** [comment]
This is an interesting topic. I would imagine that a simple distribution pattern would be to run multiple instances of the current code on multiple machine, each simulating their own set of environments. The network parameters would need to be shared using parameter servers.

**Comment by jlewi** [comment]
@danijar So basically you want to do data [parallel replicated training](https://www.tensorflow.org/deploy/distributed#replicated_training) with TensorFlow 
each of which is getting data from a set of environments running colocated with TF.

I think that would work out of the box with the [TfJob CRD](https://github.com/tensorflow/k8s). The CRD will take care of provisioning a set of workers and parameter servers. The workers can run any code (docker image); so they could use tensorflow/agents to launch a bunch of environments as subprocesses.

You could also move the environments into 1 or more sidecars and communicate via the filesystem or sockets. This might be beneficial if
  * You want better monitoring/isolation of the simulation environments compared to TF workers
  * You have different docker images for your TensorFlow process and environments

Would it be beneficial to run the simulations on different machines from the workers?

It sounds like the pattern is many simulations to 1 worker; i.e. you have N workers and each worker uses B simulations to generate a batch of size B.

If tensorflow/agents adds an RPC mode of communication, then I think K8s should be able to handle distributing both TensorFlow workers and the simulations across multiple machines.

Using [StatefulSets](https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/) you could start N * B simulations; each with a stable DNS name.  Each worker could then use B of these simulations.

**Comment by danijar** [comment]
I think in many scenarios it makes sense to simulate and train on the same machine, and just scale the number of those machines. That's mainly because it seems to reduce communication overhead significantly by only sharing parameters, not all the collected data. I'd be super curious to know if that works out of the box as you mentioned it might!

In some new scenarios we cannot simulate the environments on the same machine, let's say because the data is generated by some specialized service or on a real robot. In that case, we could implement a Gym environment that under the hood communicates with the data service via RPCs. But instead of communicating for every frame, we might want to send a policy to the data collector and get back full trajectories, which would require some more changes.

**Comment by jlewi** [comment]
> I think in many scenarios it makes sense to simulate and train on the same machine, and just scale the number of those machines. That's mainly because it seems to reduce communication overhead significantly by only sharing parameters, not all the collected data. I'd be super curious to know if that works out of the box as you mentioned it might!

So would I. Is there a simple example we could try to parallelize across multiple machines using TfJob?

**Comment by cwbeitel** [comment]
So would you be thinking of having the user make sure there are the right number of workers and remotes or abstract that (i.e. who is calculating N*B)?

```yaml
apiVersion: "tensorflow.org/v1alpha1"
kind: "TfJob"
metadata:
  name: "gym-core-job"
spec:
  replicaSpecs:
    - replicas: 1
      tfReplicaType: MASTER
      template:
        spec:
          containers:
            - image: gcr.io/tf-on-k8s-dogfood/tf_sample:dc944ff
              name: tensorflow
          restartPolicy: OnFailure
    - replicas: 5
      tfReplicaType: WORKER
      template:
        spec:
          containers:
            - image: gcr.io/tf-on-k8s-dogfood/tf_sample:dc944ff
              name: tensorflow
          restartPolicy: OnFailure
    - replicas: 20
      tfReplicaType: WORKER
      template:
        spec:
          containers:
          - name: gym-core
            image: quay.io/openai/universe.gym-core
            ports:
              - containerPort: 5900
              - containerPort: 15900
            securityContext:
              capabilities:
                privileged: true
    - replicas: 2
      tfReplicaType: PS
```
I like the StatefulSets idea but just to understand that more in 

Re StatefulSets - So each member member of the stateful set by knowing its own index and the size of the set can determine the names of pods it should connect to? If N=2, B=3, then agent i connects to pods named 'mypod-(N * B * i + 0)}'.gym-core, 'mypod-(N * B * i + 1)}'.gym-core, ..., 'mypod-(N * B * i + B-1)}'.gym-core e.g with app=gym-core and the pod basename mypod? For example in the gym context:

```python
def lookup_remote_addresses(n, b):
    global_index = # agent gets global index from environment?
    pod_name = # get pod basename from environment?
    app_name = # get app name from environment?
    return ['vnc://%s-%s.%s:5900+15900' % (pod_name, j, app_name) for j in range(n*b*global_index, n*b*global_index + b - 1)]

def main():
    env = gym.make('gym-core.Pong-v0')
    env.configure(remotes=lookup_remote_addresses(n=2, b=3))
    env = wrappers.experimental.SafeActionSpace(env)
    observation_n = env.reset()
    while True:
        action_k = [agent.act(ob) for ob in observation_k]
        observation_k, reward_k, done_k, info = env.step(action_k)
        env.render()

```
